[package]
name = "rome_lsp"
version = "0.0.0"
edition = "2021"
authors = ["Rome Tools Developers and Contributros"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.74"
serde = { version = "1.0.133", features = ["derive"] }
anyhow = "1.0.52"
indexmap = "1.8.0"
rome_fs = {  path = "../rome_fs" }
rome_service = { path = "../rome_service", features = ["serde_workspace"] }
rome_js_formatter = { path = "../rome_js_formatter" }
rome_formatter = { path = "../rome_formatter" }
rome_analyze = { path = "../rome_analyze" }
rome_diagnostics = { path = "../rome_diagnostics" }
rome_flags = { path = "../rome_flags" }
rome_rowan = { path = "../rome_rowan" }
rome_console = { path = "../rome_console" }
tower-lsp = { version = "0.17.0"}
tokio = { version = "1.15.0", features = ["full" ] }
tracing = { version = "0.1.31", default-features = false, features = ["std", "max_level_trace", "release_max_level_warn"] }
tracing-tree = "0.2.0"
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
parking_lot = "0.12.0"
futures = "0.3"

[target.'cfg(target_os = "windows")'.dependencies]
mimalloc = "0.1.29"

[dev-dependencies]
tower = { version = "0.4.12", features = ["timeout"] }
