[package]
name = "rome_lsp"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.74"
serde = { version = "1.0.133", features = ["derive"] }
anyhow = "1.0.52"
indexmap = { workspace = true }
rome_fs = {  path = "../rome_fs" }
rome_service = { path = "../rome_service" }
rome_js_formatter = { path = "../rome_js_formatter" }
rome_formatter = { path = "../rome_formatter" }
rome_analyze = { path = "../rome_analyze" }
rome_diagnostics = { path = "../rome_diagnostics" }
rome_rowan = { workspace = true }
rome_console = { workspace = true }
rome_text_edit = { path = "../rome_text_edit" }
tokio = { workspace = true, features = ["rt", "io-std"] }
tower-lsp = { version = "0.19.0" }
tracing = { workspace = true, features = ["attributes"] }
futures = "0.3"

[dev-dependencies]
tower = { version = "0.4.12", features = ["timeout"] }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
proptest = "1.0.0"
