[package]
name = "rome_lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rome_fs = {  path = "../rome_fs" }
serde_json = "1.0.74"
serde = { version = "1.0.133", features = ["derive"] }
anyhow = "1.0.52"
indexmap = "1.8.0"
rome_formatter = { path = "../rome_formatter" }
rome_analyze = { path = "../rome_analyze" }
rome_diagnostics = { path = "../rome_diagnostics" }
rome_js_parser = { path = "../rome_js_parser" }
rome_js_syntax = { path = "../rome_js_syntax" }
lspower = "1.5"
tokio = { version = "1.15.0", features = ["full" ] }
tracing = { version = "0.1.31", features = ["max_level_trace", "release_max_level_warn"] }
tracing-tree = "0.2.0"
tracing-subscriber = "0.3.5"
parking_lot = "0.12.0"
futures = "0.3"
