[package]
name = "rome_lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.74"
serde = { version = "1.0.133", features = ["derive"] }
anyhow = "1.0.52"
indexmap = "1.8.0"
rome_formatter = { path = "../rome_formatter" }
rome_analyze = { path = "../rome_analyze" }
rslint_errors = { path = "../rslint_errors", version = "0.2.0" }
rslint_parser = { path = "../rslint_parser" } 
lspower = "1.5.0"
tokio = { version = "1.15.0", features = ["full" ] }
tracing = { version = "0.1.29", features = ["max_level_trace"] }
tracing-tree = "0.2.0"
tracing-subscriber = "0.3.5"
