[package]
name = "rome_playground"
version = "0.0.0"
edition = "2021"
authors = ["Rome Tools Developers and Contributros"]
license = "MIT"

[package.metadata.wasm-pack.profile.dev]
# wasm-opt = ['-O1']

[lib]
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = { version = "0.2.79", features = ["serde-serialize"] }
js-sys = "0.3.58"
rome_service = { path = "../../crates/rome_service", features = ["serde_workspace"] }
rome_console = { path = "../../crates/rome_console" }
rome_diagnostics = { path = "../../crates/rome_diagnostics" }
