[package]
name = "rome_playground"
version = "0.0.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.79"
rome_formatter = { path = "../../crates/rome_formatter" }
rome_js_formatter = { path = "../../crates/rome_js_formatter" }
rome_js_parser = { path = "../../crates/rome_js_parser" }
rome_diagnostics = { path = "../../crates/rome_diagnostics" }
