[package]
name = "rome_playground"
version = "0.0.0"
edition = "2021"
authors = ["Rome Tools Developers and Contributros"]
license = "MIT"

[package.metadata.wasm-pack.profile.dev]
# wasm-opt = ['-O1']

[lib]
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.79"
js-sys = "0.3.58"
web-sys = "0.3.58"
rome_js_formatter = { path = "../../crates/rome_js_formatter" }
rome_formatter = { path = "../../crates/rome_formatter" }
rome_js_parser = { path = "../../crates/rome_js_parser", features = ["serde"] }
rome_js_syntax = { path = "../../crates/rome_js_syntax" }
rome_diagnostics = { path = "../../crates/rome_diagnostics" }
rome_analyze = { path = "../../crates/rome_analyze" }
rome_js_analyze = { path = "../../crates/rome_js_analyze" }
rome_console = { path = "../../crates/rome_console" }
