[package]
name = "xtask_lintdoc"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
xtask = { path = '../', version = "0.0" }
rome_analyze = { path = "../../crates/rome_analyze" }
rome_console = { path = "../../crates/rome_console" }
rome_diagnostics = { path = "../../crates/rome_diagnostics" }
rome_js_analyze = { path = "../../crates/rome_js_analyze" }
rome_js_parser = { path = "../../crates/rome_js_parser" }
rome_js_syntax = { path = "../../crates/rome_js_syntax" }
rome_service = { path = "../../crates/rome_service" }
rome_formatter = { path = "../../crates/rome_formatter" }
pulldown-cmark = { version = "0.9", default-features = false }
