[package]
name = "rome_cli"
version = "0.0.0"
edition = "2021"
authors = ["Rome Tools Developers and Contributors"]
repository = "https://github.com/rome/tools"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rome_formatter = { path = "../rome_formatter" }
rome_diagnostics = { path = "../rome_diagnostics", feature = ["serde"] }
rome_service = { path = "../rome_service" }
rome_flags = { path = "../rome_flags" }
rome_fs = { path = "../rome_fs" }
rome_console = { path = "../rome_console" }
pico-args = { version ="0.5.0", features=["eq-separator"] }
tracing = { version = "0.1.31", default-features = false, features = ["std"] }
tracing-subscriber = "0.3.6"
lazy_static = "1.4.0"
hdrhistogram = { version = "7.5.0", default-features = false }
crossbeam = "0.8.1"
thiserror = "1.0.30"
rayon = "1.5.1"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = { version = "1.0.74" }
indexmap = { version = "1.9.1", features = ["serde"] }

[dev-dependencies]
insta = "1.18.2"
tokio = { version = "1.15.0", features = ["io-util"] }
rome_lsp = { path = "../rome_lsp" }
rome_bin = { path = "../rome_bin" }
