[package]
edition = "2021"
name = "rslint_syntax"
version = "0.1.4"
authors = ["RSLint developers"]
description = "SyntaxKind and common rowan definitions for rslint_parser"
license = "MIT"
repository = "https://github.com/rslint/rslint"

[dependencies]
rome_rowan = { path = "../rome_rowan", version = "0.0.0" }
