blank_issues_enabled: false
contact_links:
  - name: ğŸ—£ï¸ Chat
    url: https://discord.gg/rome
    about: Our Discord server is active and is used for real-time discussions including contribution collaboration, questions, and more!
  - name: ğŸ¤” Support
    url: https://discord.gg/rome
    about: "This issue tracker is not for support questions. Visit our community Discord and the #support channel for assistance!"
  - name: ğŸ†˜ Code of Conduct Reports
    url: https://github.com/rome/tools/blob/main/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct
    about: Please use the contact information in Code of Conduct as issues created here are public
