[package]
name = "rome_markup"
version = "0.0.0"
description = ""
license = "MIT"
edition = "2021"
authors = ["Rome Tools Developers and Contributors"]
repository = "https://github.com/rome/tools"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.36"
quote = "1.0.14"
proc-macro-error = { version = "1.0.4", default-features = false }
