[package]
name = "rome_json_parser"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "An extremely fast JSON parser"
documentation = "https://rustdocs.rome.tools/rome_json_parser/index.html"
categories = ["parser-implementations", "development-tools"]
homepage.workspace = true

[dependencies]
rome_rowan = { workspace = true }
rome_console = { workspace = true }
rome_diagnostics = { workspace = true }
rome_json_syntax = {version = "0.0.1",  path = "../rome_json_syntax" }
rome_json_factory = { version = "0.0.1", path = "../rome_json_factory" }
rome_js_unicode_table = {version = "0.0.1",  path = "../rome_js_unicode_table" }
rome_parser = { version = "0.0.1", path = "../rome_parser" }
tracing = { workspace = true }

[dev-dependencies]
tests_macros = { path = "../tests_macros" }
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
insta = { workspace = true }

# cargo-workspaces metadata
[package.metadata.workspaces]
independent = true
