[package]
authors.workspace    = true
description          = "Utilities to create JSON AST for rome_json_parser"
documentation        = "https://rustdocs.rome.tools/rome_json_parser/index.html"
edition.workspace    = true
license.workspace    = true
name                 = "rome_json_factory"
repository.workspace = true
version              = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rome_json_syntax = { workspace = true }
rome_rowan       = { workspace = true }
