[package]
name = "xtask_codegen"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
xtask = { path = '../', version = "0.0" }
anyhow = "1.0.52"
pico-args = "0.4.2"
quote = "1.0.14"
proc-macro2 = { version = "1.0.36", features = ["span-locations"] }
ungrammar = "1.14.9"
walkdir = "2.3.2"
ureq = "2.4.0"
git2 = { version = "0.13.25", default-features = false }
filetime = "0.2.15"
termcolor = "1.1.3"
