[[cases]]
filename = "file.tsx"
invalid = [
	'<h1 role="checkbox"></h1>',
]
valid = [
	'<h1 role="article"></h1>',
]
[[cases]]
filename = "file.html"
invalid = [
	'<h1 role="checkbox"></h1>',
]
valid = [
	'<h1 role="article"></h1>',
]
