[[cases]]
		filename= "file.html"
		invalid= [
			"<span tabindex=\"1\">foo</span>",
	]
		valid= [
			"<span tabindex=\"0\">baz</span>",
			"<span tabindex=\"-1\">baz</span>",
	]
[[cases]]

		filename= "file.tsx"
		invalid= [
			"<span tabIndex='5'>foo</span>",
			"<span tabIndex={5}>foo</span>",
			"<span tabIndex={'5'}>foo</span>",
	]
		valid= [
			"<span tabIndex={0}>baz</span>",
			"<span tabIndex={-1}>baz</span>",
			"<span tabIndex='-1'>baz</span>",
			"<span tabIndex='0'>baz</span>",
			"<span tabIndex={dynamic}>baz</span>",
			"<span tabIndex={undefined}>baz</span>",
	]

