[[cases]]
filename = "file.jsx"
invalid = [
	'<a />',
	'<a><TextWrapper aria-hidden /></a>',
]
valid = [
	'<a>Anchor Content!</a>',
	'<a><TextWrapper /></a>',
	'<a dangerouslySetInnerHTML={{ __html="foo" }} />',
	'<a><TextWrapper aria-hidden={true} /> visible content</a>',
]

[[cases]]
filename = "file.html"
invalid = [
	'<a></a>',
]
valid = [
	'<a>Anchor Content!</a>',
	'<a><div aria-hidden="true"></div>visible content</a>'
]

