[[cases]]
filename = "file.tsx"
invalid = [
	'<html></html>',
	'<html {...props}></html>',
	'<html lang=""></html>',
	'<html lang={""}></html>',
	'<html lang={``}></html>',
	'<html lang={undefined}></html>',
	'<html lang={false}></html>',
	'<html lang={true}></html>',
	'<html lang={42}></html>',
]
valid = [
	'<html lang="en"></html>',
	'<html lang={language}></html>',
	'<html lang={() => language}></html>',
	'<Html lang={42}></Html>',
]

[[cases]]
filename = "file.html"
invalid = [
	'<html></html>',
	"""<html lang="
"></html>"""
]
valid = [
	'<html lang="42"></html>',
	'<html lang="en"></html>',
]

