[package]
name = "rslint_regex"
version = "0.3.0"
authors = ["RSLint developers"]
edition = "2018"
description = "RegEx parser for the ECMAScript definition"
license = "MIT"
repository = "https://github.com/rslint/rslint"

[dependencies]
bitflags = "1.2.1"
once_cell = "1.5.2"
rslint_errors = { version = "0.2", path = "../rslint_errors", optional = true }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "regex"
harness = false
