[package]
name = "rome_parser"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
description = "Shared infrastructure for Rome's parser"
repository.workspace = true
documentation = "https://rustdocs.rome.tools/rome_parser/index.html"
license.workspace = true


[dependencies]
rome_console = { version = "0.0.1", path = "../rome_console" }
rome_diagnostics = { version = "0.0.1",path = "../rome_diagnostics" }
rome_rowan = { workspace = true }
drop_bomb = "0.1.5"
