[package]
authors.workspace    = true
description          = "Shared infrastructure for Rome's parser"
documentation        = "https://docs.rs/rome_parser"
edition.workspace    = true
license.workspace    = true
name                 = "rome_parser"
repository.workspace = true
version              = "0.2.0"


[dependencies]
drop_bomb        = "0.1.5"
rome_console     = { workspace = true }
rome_diagnostics = { workspace = true }
rome_rowan       = { workspace = true }
