[package]
authors.workspace    = true
edition.workspace    = true
license.workspace    = true
name                 = "rome_json_analyze"
repository.workspace = true
version              = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static      = { workspace = true }
rome_analyze     = { workspace = true }
rome_console     = { workspace = true }
rome_diagnostics = { workspace = true }
rome_json_syntax = { workspace = true }
rome_rowan       = { workspace = true }

[dev-dependencies]
insta             = { workspace = true, features = ["glob"] }
rome_json_factory = { workspace = true }
rome_json_parser  = { workspace = true }
rome_service      = { workspace = true }
rome_test_utils   = { workspace = true }
tests_macros      = { workspace = true }
