[package]
edition = "2021"
name    = "rome_migrate"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static      = { workspace = true }
rome_analyze     = { workspace = true }
rome_diagnostics = { workspace = true }
rome_json_syntax = { workspace = true }
rome_rowan       = { workspace = true }

[dev-dependencies]
rome_json_parser = { workspace = true }
