[package]
name = "rome_migrate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rome_rowan = { workspace = true }
rome_json_syntax = { workspace = true }
rome_json_parser = { workspace = true}
rome_analyze = { path = "../rome_analyze"}
rome_diagnostics = { workspace = true}
lazy_static = { workspace = true }
