[package]
name = "rome_diagnostics"
version = "0.2.0"
authors = ["RSLint developers"]
edition = "2021"
license = "MIT"
description = "Pretty error reporting library based on codespan-reporting built for the RSLint project"

[dependencies]
rome_rowan = { path = "../rome_rowan" }
unicode-width = "0.1.9"
serde = { version = "1.0.133", optional = true, features = ["derive"] }
lsp-types = { version = "0.92.0", optional = true }
rome_text_edit = { path = "../rome_text_edit" }
termcolor = "1.1.2"
colored = "2.0.0"

[features]
lsp = ["lsp-types"]
