[package]
edition.workspace = true
name = "rome_js_parser"
version = "0.0.2"
authors.workspace = true
license.workspace = true
description = "An extremely fast ECMAScript parser for Rome, forked from the RSlint project"
repository.workspace = true
documentation = "https://rustdocs.rome.tools/rome_js_parser/index.html"
categories = ["parser-implementations", "development-tools"]
homepage.workspace = true

[dependencies]
rome_console = { version = "0.0.1", path = "../rome_console" }
rome_diagnostics = { version = "0.0.1", path = "../rome_diagnostics" }
rome_js_syntax = { version = "0.0.2", path = "../rome_js_syntax" }
rome_js_factory = { version = "0.0.2", path = "../rome_js_factory" }
rome_js_unicode_table = { version = "0.0.1", path = "../rome_js_unicode_table" }
rome_rowan = { workspace = true }
rome_parser = { version = "0.0.1", path = "../rome_parser" }
drop_bomb = "0.1.5"
bitflags.workspace = true
indexmap = { workspace = true }
cfg-if = "1.0.0"
smallvec = { version = "1.8.0", features = ["union", "const_new"] }
tracing = { workspace = true }

[dev-dependencies]
tests_macros = { path = "../tests_macros" }
expect-test = "1.2.2"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

[features]
serde = ["rome_js_syntax/serde"]
tests = []

# cargo-workspaces metadata
[package.metadata.workspaces]
independent = true
