[package]
name = "rome_js_semantic"
version = "0.0.0"
description = "Semantic model for the JavaScript language"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
rome_rowan = { path = "../rome_rowan" }
rome_js_syntax = { path = "../rome_js_syntax" }
rust-lapper = "1.0.1"

[dev-dependencies]
rome_markup = { path = "../rome_markup" }
rome_diagnostics = { path = "../rome_diagnostics" }
rome_console = { path = "../rome_console" }
rome_js_parser = { path = "../rome_js_parser" }
