[package]
name = "rome_js_formatter"
version = "0.0.0"
edition = "2021"
authors = ["Rome Tools Developers and Contributros"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
rome_js_syntax = { path = "../rome_js_syntax" }
rome_formatter = { path = "../rome_formatter" }
rome_rowan = { path = "../rome_rowan" }
tracing = { version = "0.1.31", default-features = false, features = ["std"] }
unicode-width = "0.1.9"
serde = { version = "1.0.136", features = ["derive"], optional = true }

[dev-dependencies]
rome_fs = { path = "../rome_fs" }
rome_service = { path = "../rome_service" }
rome_js_parser = { path = "../rome_js_parser" }
rome_js_factory = { path = "../rome_js_factory" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tests_macros = { path = "../tests_macros" }
insta = { version = "1.14.0", features = ["glob"] }
rome_diagnostics = { path = "../rome_diagnostics" }
countme = { version = "3.0.0", features = ["enable"] }
parking_lot = "0.12.0"
similar = "2.1.0"
similar-asserts = "1.2.0"
ctor = "0.1.21"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
iai = "0.1.1"

[[bench]]
name = "iai"
harness = false
