[package]
name = "rome_json_formatter"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
categories = ["development-tools"]
documentation = "https://rustdocs.rome.tools/rome_js_formatter/index.html"
description = "Rome's JSON formatter"
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rome_json_syntax = {  version = "0.0.1", path = "../rome_json_syntax" }
rome_formatter = { workspace = true }
rome_rowan = { workspace = true }

[dev-dependencies]
rome_parser = { version = "0.0.1", path = "../rome_parser" }
rome_formatter_test = {path = "../rome_formatter_test"}
rome_fs = { path = "../rome_fs" }
rome_json_parser = { workspace = true }
rome_json_factory = { path = "../rome_json_factory" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tests_macros = { path = "../tests_macros" }
insta = { workspace = true, features = ["glob"] }
rome_diagnostics = { workspace = true }
countme = { workspace = true, features = ["enable"] }

# cargo-workspaces metadata
[package.metadata.workspaces]
independent = true
