[package]
name = "rome_rowan"
version = "0.0.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
repository = "https://github.com/rust-analyzer/rowan"
license = "MIT OR Apache-2.0"
description = "Library for generic lossless syntax trees"
edition = "2021"

[dependencies]
rustc-hash = "1.0.1"
hashbrown = { version = "0.11.2", features = [
    "inline-more",
], default-features = false }
text-size = "1.1.0"
memoffset = "0.6"
countme = "2.0.0"
init_array = "0.2.1"

serde = { version = "1.0.89", optional = true, default-features = false }

[dev-dependencies]
m_lexer = "0.0.4"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
serde_json = "1.0.69"

[features]
serde1 = ["serde", "text-size/serde"]
