[package]
name = "rome_rowan"
version = "0.0.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
repository = "https://github.com/rust-analyzer/rowan"
license = "MIT OR Apache-2.0"
description = "Library for generic lossless syntax trees"
edition = "2021"

[dependencies]
rustc-hash = "1.1.0"
hashbrown = { version = "0.12.3", features = [
    "inline-more",
], default-features = false }
rome_text_size = { path = "../rome_text_size" }
memoffset = "0.6.5"
countme = "3.0.0"
serde = { version = "1.0.133", optional = true, default-features = false }
rome_text_edit = { path = "../rome_text_edit" }
schemars = { version = "0.8.10", optional = true }

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
serde_json = "1.0.79"
iai = "*"

[features]
serde = ["dep:serde", "schemars", "rome_text_size/serde"]
batch_log = []

[[bench]]
name = "mutation"
harness = false
