[package]
name = "rome_rowan"
version = "0.0.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
repository = "https://github.com/rust-analyzer/rowan"
license = "MIT OR Apache-2.0"
description = "Library for generic lossless syntax trees"
edition = "2021"

[dependencies]
rustc-hash = "1.1.0"
hashbrown = { version = "0.11.2", features = [
    "inline-more",
], default-features = false }
text-size = "1.1.0"
memoffset = "0.6.5"
countme = "3.0.0"
thiserror = "1.0.30"

serde = { version = "1.0.133", optional = true, default-features = false }

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

[features]
serde1 = ["serde", "text-size/serde"]
