filename= "file.ts"
invalid= [
	"function foo(x= boolean) { return !!x; }",
	"function foo(x= boolean) { return x === true; }",
	"function foo(x= boolean) { return false === x; }",
	"function foo(x= boolean, y= boolean) { return (x || y) === true }",
]
valid= [
	"function foo(x?= boolean) { return !!x; }",
	"function foo(x= boolean | number) { return x === true; }",
	"function foo(x= boolean | undefined) { return false === x; }",
]
