name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  typescript:
    runs-on: ubuntu-latest
    name: TypeScript Check

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Run TypeScript
        run: node ./node_modules/.bin/tsc --noEmit

  ci:
    name: Lint & Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Check Prettier formatting
        run: ./scripts/prettier-check
      - name: Run Rome ci
        run: ./scripts/dev-rome ci

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [typescript, ci]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Build release
        run: ./scripts/build-release dist

      - name: Create tarball
        run: tar -C dist -czvf dist.tar.gz .

      - name: Upload tarball
        uses: actions/upload-artifact@v1
        with:
          name: package.tgz
          path: dist.tar.gz
