name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: rome ci (ubuntu-latest)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'
          all_commits: true
      - name: rome ci
        run: ./rome ci --changed=main

  tests:
    name: rome test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'
      - name: rome test
        run: ./rome test --freeze-snapshots

  typescript:
    runs-on: ubuntu-latest
    name: TypeScript Check

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'
      - name: Run TypeScript
        run: node ./node_modules/.bin/tsc --noEmit

  generated:
    name: Generated Files Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'
      - name: Check if generated files need to be updated
        run: ./rome run scripts/generate-all-files
