
# Jobs run on pull request in js folders
name: Pull request JS
on:
  pull_request:
    branches:
      - main
    paths: # Only run when changes are made to js code
      - 'website/**'
      - 'editors/**'
      - 'npm/**'

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  format-js:
    name: Check JS Files
    runs-on: ubuntu-latest
    steps:
      - name: Install Rome
        uses: rome/setup-rome@v0.4
        with:
          version: preview

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Rome Format
        run: rome ci editors website npm/rome/src
  type-check:
    name: Type-check JS Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          submodules: false
      - uses: jetli/wasm-pack-action@v0.3.0
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7
      - name: Install libraries
        working-directory: website/playground
        run: pnpm i
      - name: Build Wasm
        working-directory: website/playground
        run: pnpm build
      - name: Type check playground
        working-directory: website/playground
        run: pnpm tsc
      - name: Type check Node API
        working-directory: npm/rome
        run: pnpm tsc
