[package]
name = "rome_core"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rome_fs = { version = "0.0.0", path = "../rome_fs" }
rome_console = { version = "0.0.0", path = "../rome_console" }
